package com.tambo.sistematambo.response;

public record RutaEntregaResponse(
        Long id,
        String nombre,
        String zona,
        String repartidor,
        Long pedidoId,
        Long transferenciaId,
        String vehiculo,
        String tipoVehiculo,
        String placa,
        Integer capacidadVehiculo,
        Integer cantidadCarga,
        String origen,
        String destino,
        String fechaEntrega,
        Integer pedidos,
        String estado,
        String horaSalida,
        String horaEstimadaLlegada,
        String horaEntregaReal,
        String ubicacionActual,
        String observaciones,
        String incidencias,
        String estadoGps,
        String evidenciaEntrega,
        String firmaDigital,
        String fotoEntrega,
        Boolean vehiculoActivo,
        Boolean conductorBloqueado,
        Boolean confirmacionEntrega,
        Integer progreso) {
}
